CREATE TABLE `menu` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`restaurant` ENUM('ZAMECKA','KOZLOVNA','MEXICO','DELOVA-KOULE','JIDELNA','LUCIE','RIEGER') NOT NULL,
	`date` DATE NOT NULL,
	`name` VARCHAR(120) NOT NULL,
	`price` SMALLINT(6) NULL DEFAULT NULL,
	`type` ENUM('SOUP','MEAL') NOT NULL,
	PRIMARY KEY (`id`)
)
ENGINE = InnoDB;
